
#Fail System

console_error_message: '&8[&c*&8] &cYou are unable to execute these commands!'

no_perm_error: '&cYou do not have the permission to execute this command!'

################################################################################

#Join System

firstjoin_message: '&a<player> &7has joined the server for the first time!'

join_message: '&e<player> &7has joined the server!'
################################################################################

#Fly System

FlyCmd:
  fly_active: '&8[&a*&8] &7You have &aenabled &7flight!'
  fly_deactive: '&8[&c*&8] &7You have &cdisabled &7flight!'
   
