console_error_message: '&8[&c*&8] &cYou are unable to execute this command!'
no_perm_error: '&8[&c*&8] &cYou are unable to execute this command!'

#Fly Command
FlyCmd:
   fly_active: '&8[&a*&8] &7You have &aenabled &7fly!'
   fly_deactived: '&8[&a*&8] &7You have &cdisabled &7fly!'
   
#Join System

firstjoin_message: '&a<player> &7has joined the server for the first time!'
join_message: '&e<player> &7has joined the server!'

#Website
WebsiteCmd:
   website: '&4Link to website: &5https://11c.org/'

#Youtube
YoutubeCmd:
   youtube: '&4The official youtube is: &5https://www.youtube.com/channel/UCnqhHNB_aG58RqkeCxFfA9w/'
   
#Leave System
LeaveListener:
   leave_event: '&a<player> &7has left the server.'
   
#Gamemode System
GmSys:
   c: '&8[&a*&8] &7You have &aentered &7Creative mode!'
   s: '&8[&a*&8] &7You have &aentered &7Survival mode!'
   sp: '&8[&a*&8] &7You have &aentered &7Spectator mode!'
   ad: '&8[&a*&8] &7You have &aentered &7Adventure mode!'

#About Command   
AboutCmd:
   about: "&5Plugin Name: &6c11C Plugin\n &5Plugin Version: &60.7.1\n Hope you have a fun time!"
   
#Help Command
HelpCmd:
   help: "&6About: &fInformation of 11C's Plugin \n  &6Fly: &fAllow Flight \n &6CHelp: &fInformation of 11C's Commands \n &6Website: &fLink to 11C's Official Website\n &6Discord: &fLink to 11C's Official Discord \n &6Credits: &fWho worked on 11C Plugin \n &6Youtube: &f11C's Official Youtube \n &6Hub: &fTeleports you to the server Hub \n &6GMS: &fSwitches your gamemode to survival \n &6GMSP: &fSwitches your gamemode to spectator \n &6GMC: &fSwitches your gamemode to creative \n &6GMAD: &fSwitches your gamemode to adventure"
